### ISSUE TITLE
Zap-cli start does not properly handle -host argument

### ISSUE THREAD

**Issue by westeve** [Grunny/zap-cli#56] opened 2018-06-08 19:09 UTC
I'm attempting to use zap-cli to connect to a url other than localhost, and I'm attempting to do so by using the command ``zap-cli start -o "-host $LOCAL_PROXY -config api.key=30690"`` where LOCAL_PROXY  is a valid IP address to connect to. When I attempt this, zap-cli times out and tells me it failed to connect, and then running zap-cli status tells me that ZAP is not running. 

However if I check zap.log,the last printed message is that ZAP is now listening on the port and url I want it to listen to. This happens whether my ZAP_URL environment variable is localhost or the url I want to listen to. Additionally, if I set ZAP_URL to my desired URL, I get back ``WARN org.zaproxy.zap.extension.api.API  - Request to API URL http://172.25.0.6:8085/ from 172.25.0.6 not permitted`` which means that localhost is probably the better one to use as my environment variable for this purpose. 

Additionally, if I set ZAP_URL to my desired URL and don't set a host argument, it times out, then if I check zap.log the printed message is that I'm now listening on localhost and my specified port. Zap-cli starts fine if I supply no host argument and have my ZAP_URL be localhost or I have both arguments as localhost. From all this I'm guessing that the check that the zap daemon is running isn't handled properly with hosts other than localhost, maybe it's checking from a zap process on the wrong address.

**Comment by Grunny** [comment] 2018-06-22 17:39
Hi @westeve! ZAP by default does not allow you to connect to its API from addresses other than localhost (and `http:/zap`) by default. So, you also need to add the IP you want to connect to ZAP from to the allowed addresses. You can do this manually in the GUI by going to "Tools -> Options -> API" and adding the IP to "Addresses permitted to use the API". Or you can also do it in the start options. So to use the IP `172.25.0.6` as in your example, you could start ZAP like this:
```
$ zap-cli --zap-url 'http://172.25.0.6' -v start -o '-host 172.25.0.6 -config api.addrs.addr.name=172.25.0.6'
```

Though the `--zap-url` param is unneeded if the `ZAP_URL` environment variable is set. This will then allow you to connect to the ZAP API from `172.25.0.6` rather than localhost. If you're in a trusted/isolated environment, you can also let all IPs use ZAP with the following start options `-config api.addrs.addr.name=.* -config api.addrs.addr.regex=true`.

I hope that helps!

**Comment by westeve** [comment] 2018-06-28 19:08
I tried the command as written (``zap-cli --zap-url 'http://135.22.97.242' -v start -o '-host 135.22.97.242 -config api.addrs.addr.name=135.22.97.242'``) and I get the same problem. Zap-cli claims it timed out waiting for ZAP but then when you check the log it shows ``8084 [ZAP-daemon] INFO org.zaproxy.zap.DaemonBootstrap  - ZAP is now listening on 135.22.97.242:8090`` which means that I'm still having the problem.

**Comment by Grunny** [comment] 2018-06-28 19:13
Hmm, I can't reproduce any issues with using `-host` as long as the IP address is permitted to use the API. When ZAP is running after saying it's listening on `135.22.97.242:8090`, does opening `http://135.22.97.242:8090/` in your browser work? All `zap-cli` does to check it's running is request the base API URL and confirm it responds properly, so first thing to check would be that `http://135.22.97.242:8090/` shows the ZAP API docs when viewed in a browser.

**Comment by Grunny** [comment] 2018-09-06 17:45
Closing for now as not reproducible. Please reopen if it is still happening for you.

**Closed by Grunny** 2018-09-06 17:45 UTC
